export const SET_STATE_ANSWERS = "SET_STATE_ANSWERS";
export const SET_STATE_BLOCKS = "SET_STATE_BLOCKS";
export const SET_STATE_BLOCK = "SET_STATE_BLOCK";
export const SET_STATE_QUESTION = "SET_STATE_QUESTION";
export const SET_STATE_QUESTIONS = "SET_STATE_QUESTIONS";